name: taralists
include:
  - path: ./taracert/compose.yml
services:
  database:
    image: postgres:18-alpine
    volumes:
      - mailman-database-data:/var/lib/postgresql/data
    secrets:
      - dbpass
    environment:
      POSTGRES_DB: ${DBNAME}
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD_FILE: /run/secrets/dbpass
    networks:
      default:
        aliases:
          - taralists-database
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --dbname ${DBNAME} --username ${DBUSER}" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5

  mailman-core:
    build: mailman-core
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - mailman-core-data:/opt/mailman/
      - ./mailman-core/mailman-extra.cfg:/opt/mailman/mailman-extra.cfg
    environment:
      DATABASE_URL: postgresql://${DBUSER}:${DBPASS}@taralists-database/${DBNAME}
      DATABASE_TYPE: postgres
      DATABASE_CLASS: mailman.database.postgresql.PostgreSQLDatabase
      HYPERKITTY_API_KEY: ${HYPERKITTY_API_KEY}
      HYPERKITTY_URL: http://taralists-mailman-web:8000/hyperkitty
      MTA: postfix
      TZ: ${TZ}
    networks:
      default:
        ipv4_address: ${IPV4_NETWORK:-172.22.1}.241
        aliases:
          - taralists-mailman-core
    restart: always
    stop_grace_period: 30s

  mailman-web:
    image: maxking/mailman-web:0.5
    depends_on:
      database:
        condition: service_healthy
      mailman-core:
        condition: service_started
    volumes:
      - mailman-web-data:/opt/mailman-web-data
      - ./mailman-web/settings_local.py:/opt/mailman-web-data/settings_local.py
    environment:
      DATABASE_URL: postgresql://${DBUSER}:${DBPASS}@taralists-database/${DBNAME}
      DATABASE_TYPE: postgres
      HYPERKITTY_API_KEY: ${HYPERKITTY_API_KEY}
      SECRET_KEY: ${SECRET_KEY}
      MAILMAN_HOSTNAME: ${IPV4_NETWORK:-172.22.1}.241
      SERVE_FROM_DOMAIN: ${SERVER_HOSTNAME}
      MAILMAN_ADMIN_USER: ${MAILMAN_ADMIN_USER}
      MAILMAN_ADMIN_EMAIL: ${MAILMAN_ADMIN_EMAIL}
      TZ: ${TZ}
    networks:
      default:
        aliases:
          - taralists-mailman-web
    restart: always

  postfix:
    build: postfix
    depends_on:
      mailman-core:
        condition: service_started
    volumes:
      - mailman-core-data:/opt/mailman/:ro
    environment:
      SERVER_HOSTNAME: ${SERVER_HOSTNAME}
      RELAYHOST: ${RELAYHOST:-taramail-postfix}
      RELAYHOST_PORT: ${RELAYHOST_PORT:-25}
    networks:
      default:
        aliases:
          - taralists-postfix
      taramail:
        aliases:
          - taralists-postfix
    restart: always

  nginx:
    build: nginx
    depends_on:
      certbot:
        condition: service_healthy
      mailman-web:
        condition: service_started
    volumes:
      - certbot-www:/web:ro
      - certbot-certs:/etc/letsencrypt:ro
      - mailman-web-data:/opt/mailman-web-data:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:z
    environment:
      SERVER_HOSTNAME: ${SERVER_HOSTNAME}
      IPV4_NETWORK: ${IPV4_NETWORK:-172.22.1}
    networks:
      default:
        ipv4_address: ${IPV4_NETWORK:-172.22.1}.240
        aliases:
          - taralists-nginx
    restart: always

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-taralists
    ipam:
      driver: default
      config:
        - subnet: ${IPV4_NETWORK:-172.22.1}.0/24
  taramail:
    external: true
    name: taramail_default

volumes:
  certbot-certs:
  certbot-www:
  mailman-core-data:
  mailman-web-data:
  mailman-database-data:

secrets:
  dbpass:
    environment: DBPASS
