name: taralists
include:
  - path: ./taracert/compose.dev.yml
services:
  database:
    depends_on: {}

  mailman-core:
    depends_on:
      database:
        condition: service_started

networks:
  taramail:
    external: false
