name: taralists
include:
  - path: ./taracert/compose.dev.yml
services:
  database:
    depends_on: {}

  mailman-core:
    depends_on:
      database:
        condition: service_started

  mailman-web:
    environment:
      DJANGO_ALLOWED_HOSTS: "*"
      MAILMAN_HOST_IP: "*"

networks:
  taramail:
    external: false
